name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "pwd..."
        pwd
        echo "ls..."
        ls
        echo "ls parent..."
        ls ..
        echo "gradle..."
        gradlew shadowJar
